run:
  timeout: 5m
  go: "1.25"

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - goconst
    - gofmt
    - misspell

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment
  errcheck:
    check-type-assertions: true
    exclude-functions:
      - (*go.uber.org/zap.Logger).Sync
  goconst:
    min-len: 3
    min-occurrences: 4
  misspell:
    ignore-words:
      - coordinare
      - automatico
      - acquisito
      - simulatore
      - possibile
      - accumulare
      - correnti
      - responsabile
      - configurato
      - combinato
      - simulato

issues:
  max-issues-per-linter: 50
  max-same-issues: 5
  exclude-rules:
    - source: "^\\s*//"
      linters:
        - misspell
