-- MONEYMAKER V1 Database Initialization
-- TimescaleDB hypertables, audit log, and core schema.

-- Enable TimescaleDB extension
CREATE EXTENSION IF NOT EXISTS timescaledb;

-- ============================================================
-- Market Data: OHLCV bars stored as hypertable
-- ============================================================
CREATE TABLE IF NOT EXISTS ohlcv_bars (
    time        TIMESTAMPTZ     NOT NULL,
    symbol      TEXT            NOT NULL,
    timeframe   TEXT            NOT NULL,  -- M1, M5, M15, H1, H4, D1
    open        NUMERIC(20,8)  NOT NULL,
    high        NUMERIC(20,8)  NOT NULL,
    low         NUMERIC(20,8)  NOT NULL,
    close       NUMERIC(20,8)  NOT NULL,
    volume      NUMERIC(20,8)  NOT NULL DEFAULT 0,
    tick_count  INTEGER         DEFAULT 0,
    spread_avg  NUMERIC(10,5)  DEFAULT 0,
    source      TEXT            NOT NULL DEFAULT 'unknown'
);

SELECT create_hypertable('ohlcv_bars', 'time',
    chunk_time_interval => INTERVAL '1 day',
    if_not_exists => TRUE
);

CREATE INDEX IF NOT EXISTS idx_ohlcv_symbol_time
    ON ohlcv_bars (symbol, timeframe, time DESC);

-- ============================================================
-- Market Data: Tick-level data
-- ============================================================
CREATE TABLE IF NOT EXISTS market_ticks (
    time        TIMESTAMPTZ     NOT NULL,
    symbol      TEXT            NOT NULL,
    bid         NUMERIC(20,8)  NOT NULL,
    ask         NUMERIC(20,8)  NOT NULL,
    last_price  NUMERIC(20,8),
    volume      NUMERIC(20,8)  DEFAULT 0,
    spread      NUMERIC(10,5),
    source      TEXT            NOT NULL DEFAULT 'unknown',
    flags       INTEGER         DEFAULT 0
);

SELECT create_hypertable('market_ticks', 'time',
    chunk_time_interval => INTERVAL '1 hour',
    if_not_exists => TRUE
);

CREATE INDEX IF NOT EXISTS idx_ticks_symbol_time
    ON market_ticks (symbol, time DESC);

-- ============================================================
-- Trading: Signals generated by Algo Engine
-- ============================================================
CREATE TABLE IF NOT EXISTS trading_signals (
    id              BIGSERIAL       PRIMARY KEY,
    signal_id       TEXT            UNIQUE NOT NULL,
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    symbol          TEXT            NOT NULL,
    direction       TEXT            NOT NULL,  -- BUY, SELL, HOLD
    confidence      NUMERIC(5,4)   NOT NULL,
    suggested_lots  NUMERIC(10,4),
    stop_loss       NUMERIC(20,8),
    take_profit     NUMERIC(20,8),
    model_version   TEXT,
    regime          TEXT,
    source_tier     TEXT,
    reasoning       TEXT,
    risk_reward     NUMERIC(8,4)
);

CREATE INDEX IF NOT EXISTS idx_signals_symbol_time
    ON trading_signals (symbol, created_at DESC);

-- ============================================================
-- Trading: Executed trades (feedback loop)
-- ============================================================
CREATE TABLE IF NOT EXISTS trade_executions (
    id              BIGSERIAL       PRIMARY KEY,
    order_id        TEXT            UNIQUE NOT NULL,
    signal_id       TEXT            REFERENCES trading_signals(signal_id),
    executed_at     TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    symbol          TEXT            NOT NULL,
    direction       TEXT            NOT NULL,
    requested_price NUMERIC(20,8),
    executed_price  NUMERIC(20,8)  NOT NULL,
    quantity        NUMERIC(10,4)  NOT NULL,
    stop_loss       NUMERIC(20,8),
    take_profit     NUMERIC(20,8),
    status          TEXT            NOT NULL,  -- FILLED, REJECTED, CANCELLED, etc.
    slippage_pips   NUMERIC(10,4),
    commission      NUMERIC(10,4),
    swap            NUMERIC(10,4),
    profit          NUMERIC(20,8),
    close_price     NUMERIC(20,8),
    closed_at       TIMESTAMPTZ,
    rejection_reason TEXT
);

CREATE INDEX IF NOT EXISTS idx_executions_signal
    ON trade_executions (signal_id);
CREATE INDEX IF NOT EXISTS idx_executions_symbol_time
    ON trade_executions (symbol, executed_at DESC);

-- ============================================================
-- Audit Log: Append-only with SHA-256 hash chain
-- ============================================================
CREATE TABLE IF NOT EXISTS audit_log (
    id          BIGSERIAL       PRIMARY KEY,
    created_at  TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    service     TEXT            NOT NULL,
    action      TEXT            NOT NULL,
    entity_type TEXT,
    entity_id   TEXT,
    details     JSONB           NOT NULL DEFAULT '{}',
    prev_hash   TEXT            NOT NULL,
    hash        TEXT            NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_audit_service_time
    ON audit_log (service, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_entity
    ON audit_log (entity_type, entity_id) WHERE entity_type IS NOT NULL;

-- Prevent UPDATE and DELETE on audit_log (append-only)
CREATE OR REPLACE FUNCTION prevent_audit_modification()
RETURNS TRIGGER AS $$
BEGIN
    RAISE EXCEPTION 'Audit log is append-only. Updates and deletes are not permitted.';
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER audit_no_update
    BEFORE UPDATE ON audit_log
    FOR EACH ROW EXECUTE FUNCTION prevent_audit_modification();

CREATE TRIGGER audit_no_delete
    BEFORE DELETE ON audit_log
    FOR EACH ROW EXECUTE FUNCTION prevent_audit_modification();

-- ============================================================
-- Compression policies for older data
-- ============================================================
ALTER TABLE ohlcv_bars SET (
    timescaledb.compress,
    timescaledb.compress_segmentby = 'symbol,timeframe'
);

SELECT add_compression_policy('ohlcv_bars', INTERVAL '7 days', if_not_exists => TRUE);

ALTER TABLE market_ticks SET (
    timescaledb.compress,
    timescaledb.compress_segmentby = 'symbol'
);

SELECT add_compression_policy('market_ticks', INTERVAL '1 day', if_not_exists => TRUE);
